$(document).ready(function(){

    var arrLang = {
        'rus': {
            'h1': 'Натуральная, традиционная, вкусная чёрная икра',
            'about': 'О нас',
            'about_text': 'Ещё со времён греческого философа Эпикура чёрная икра считалась синонимом изысканности и удовольствия. Спустя 2000 лет мы повторяем этот принцип и делаем то, что называют доступной роскошью. Baku Caviar™ получают из классических каспийских осетров. Как ценители, мы гордимся тем, что нам удаётся поддерживать высокое качество и сохранять натуральный вкус.',
            'our': 'Наше наследие',
            'our_text': 'Мы ведём свою историю с 1954, когда впервые в Азербайджане был построен завод по разведению осетровых. Он расположен в Нефтчалинском районе в природном заповеднике на берегу Каспия, и мы до сих пор производим там нашу продукцию. В советское время нашу икру поставляли в Кремль. Также одним из самых известных поклонников именно нашей икры был Сэр Уинстон Черчилль.',
            'our_caviar': 'Наша икра',
            'our_caviar_text': 'Икра доступна в жестяных банках 20, 50, 125, 250, 500 грамм, 1 кг и в стеклянных банках 113 грамм.',
            'caviar_text_1': 'Русский осётр даёт нам исключительную икру, самую крупную по размерам. Упругая, с платиновым отливом и нежным сливочным вкусом, напоминающим белужью. Её добывают их взрослых особей самого ценного и изящного русского осетра.',
            'caviar_text_2': 'Этот сорт добывают из русского осетра, который первый раз идёт на нерест. Икринки среднего размера обладают лёгким янтарным оттенком и невероятно нежным вкусом грецкого ореха со сливками. Именно эту икру можно встретить чаще всего.',
            'caviar_text_3': 'Белуга — самая большая среди осетровых и настолько редкая, что в год обычно вылавливается не больше 100 рыб. До 25% массы тела занимает икра, которую белуга даёт только к 25–40 годам. Сами икринки большие и зернистые, а их цвет варьируется от почти чёрного до светло-серого, и чем светлее икра, тем больше она ценится.',
            'caviar_text_4': 'Севрюга занимает третье место среди осетровых. Её не спутать с другими, ведь она маленькая, темнее других и обладает узким вытянутым носом. Она дала торговое название самой мелкой, тёмной и, по мнению некоторых экспертов, самой вкусной чёрной икре. У неё яркий морской вкус с нотками румяного хлеба, что делает икру идеальной для канапе.',
            'caviar_text_5': 'Спрессованная чёрная икра, известная как «паюсная» — достаточно редкая и изысканная — представляет собой однородную плотную солоноватую массу. Получается из идеальных мелких цельных икринок сияющего чёрно-серого цвета. Её насыщенный вкус вобрал в себя саму суть чёрной икры. В кулинарии называется «икорным трюфелем».',
            'delivery': 'Доставка икры',
            'delivery_text': 'Вы можете заказать нашу икру с доставкой курьером в городе Баку. Для этого позвоните нам или заполните форму онлайн',
            'delivery_text_btn': 'Заказать икру',
            'nature': 'Забота о природе',
            'nature_text_1': 'Самкам осетровых требуется 8–9 лет, чтобы достичь половой зрелости. Эти рыбы могут доживать до 150 лет, а в год выпускать от 250 000 до 400 000 икринок. Но осетровые находятся под угрозой исчезновения. Поэтому Baku Caviar™ поддерживает создание в Азербайджане морского заказника в устье рек Кура и Араз.',
            'nature_text_2': 'Мы осознанно относимся к производству и заботимся о природе. Покупая нашу икру, вы помогаете восстановить природные ресурсы Каспия: с каждой проданной банки мы выпускаем в море 10 мальков осетра.',
            'buy': 'Где купить',
            'buy_text': 'Купить и попробовать нашу икру вы можете в лучших отелях и ресторанах города Баку и Азербайджана. Если вы не успели приобрести Baku Caviar™ в городе, то вы всегда сможете это сделать в Duty Free Shop международного аэропорта имени Гейдар Алиева г. Баку.',
            'menu_1': 'О нас',
            'menu_2': 'Наследие',
            'menu_3': 'Наша икра',
            'menu_4': 'Забота о природе',
            'menu_5': 'Где купить',
            'menu_6': 'Контакты',
            'order': 'Заказать икру',
            'name': 'Имя*',
            'phone': 'Телефон*',
            'adress': 'Адрес*',
            'caviar': 'Икра',
            'package': 'Упаковка и вес',
            'Tin1': 'Банка, 20 гр.',
            'Tin2': 'Банка, 50 гр.',
            'Tin3': 'Банка, 125 гр.',
            'Tin4': 'Банка, 250 гр.',
            'Tin5': 'Банка, 500 гр.',
            'Tin6': 'Банка, 1 кг',
            'glass1': 'Стекло, 56 гр.',
            'glass2': 'Стекло, 113 гр.',
            'glass3': 'Стекло, 250 гр.',
            'send': 'Отправка'
        },
        'aze': {
            'h1': 'Təbii, ənənəvi, dadlı qara kürü',
            'about': 'Biz kimik',
            'about_text': 'Hələ qədim yunan filosofu Epikurun zamanından bəri qara kürü zəraflik və həzzin sinonimi hesab edilirdi. 2000 il sonra biz bu prinsipi təkrarlayır və əlçatan lüks adlandırılan bir məhsulu ərsəyə gətiririk. Baku Caviar™ kürüləri klassik Xəzər nərəsindən əldə edilir. Bu işin bilicisi olaraq, yüksək keyfiyyəti və təbii dadı qoruyub saxlaya bildiyimiz üçün qürur duyuruq',
            'our': 'İrsimiz',
            'our_text': 'Bizim tariximiz Azərbaycanda nərəkimilərin yetişdirilməsi üzrə ilk zavodun inşa edildiyi 1954-cü ildən bəri davam edir. Zavod Neftçala rayonunda, Xəzərin sahilindəki təbii qoruqda yerləşir və biz hələ də məhsullarımızı orada istehsal edirik. Sovet dövründə bizim kürümüz Kremlə idxal edilirdi. Həmçinin məhz bizim kürümüzün ən məşhur pərəstişkarlarından biri ser Uinston Çörçill idi.',
            'our_caviar': 'Bizim kürümüz',
            'our_caviar_text': 'Kürü 20 qr, 50, 125, 250, 500 qr,1 kq çəkidə metal qablaşdırmada və 56 və 113 qr. şüşə qablaşdırmada satılır.',
            'caviar_text_1': 'Rus nərəsi bizə ölçülərinə görə ən iri olan müstəsna kürü bəxş edir. Elastik, platin parıltılı və zərif qaymaqlı dada malik olan bu kürü ağ balığın kürüsünü xatırladır. O, ən qiymətli və nəfis rus nərəsinin yaşlı fərdlərindən əldə edilir.',
            'caviar_text_2': 'Bu sort yetkinlik dövrünə çatmış rus nərəsindən əldə edilir. Orta ölçülü kürü dənəcikləri zərif kəhrəba rəng çalarına malikdir və inanılmaz dərəcədə zərif olan qaymaqlı qoz dadı verir. Məhz bu kürüyə daha tez-tez rast gəlmək olar.',
            'caviar_text_3': 'Ağ balıq - nərəkimilər arasında ən böyüyüdür və o qədər nadir balıqdır ki, adətən, il ərzində ən çox 100 balıq ovlanır. Bədəninin kütləsinin 25%-ni kürü tutur. Ağ balıq bu kürünü yalnız 25-40 yaşında verir. Kürü dənəciklərinin özü böyük və dənəvərdir, onların rəngi isə, demək olar ki, qaradan açıq boza kimi dəyişir. Kürünün rəngi nə qədər açıqdırsa, o, bir o qədər qiymətli hesab edilir',
            'caviar_text_4': 'Sevruqa (uzunburun) nərəkimilər arasında üçüncü yerdədir. Onu başqa balıqlarla səhv salmaq olmur, çünki o, kiçikdir, digərlərindən daha tünd rəngdədir və ensiz, irəli çıxmış uzun buruna malikdir. Ən xırda, tünd və bəzi ekspertlərin fikrincə, dünyanın ən ləzzətli qara kürüsünün ticarət adı bu balıqdan götürülmüşdür. Onda qızarmış çörək notları ilə dəniz məhsulları dadı hiss olunur ki, bu da kürünü kanape üçün ideal edir.',
            'caviar_text_5': 'Nəfis və nadir tapılan "payusnaya" kimi tanınan preslənmiş qara kürü həmcins, sıx və duzlutəhər kütlədən ibarətdir. Parlaq qara-boz rəngli ideal və xırda kürü dənəciklərindən əldə edilir. Onun zəngin dadı özündə qara kürünün əsl mahiyyətini birləşdirir. Kulinariyada onu "kürü tryufeli" adlandırırlar.',
            'delivery': 'Kürünün çatdırılması',
            'delivery_text': 'Kürümüzü sifariş edərək Bakı şəhəri daxilində kuryer vasitəsi ilə əldə edə bilərsiniz. Bunu etmək üçün bizə zəng edin və ya online formanı doldurun.',
            'delivery_text_btn': 'Kürünü sifariş etmək',
            'nature': 'Təbiətə qayğı',
            'nature_text_1': 'Dişi nərəkimilərə cinsi yetkinliyə çatmaq üçün 8-9 il lazımdır. Bu balıqlar 150 ilədək yaşaya, ildə isə 250 000-dən 400 000-dək kürü dənəciyi verə bilirlər. Lakin nərəkimilər yox olmaq təhlükəsi ilə üz-üzədirlər. Bun görə də Baku Caviar™ Azərbaycanda Kür və Araz çaylarının hövzəsində dəniz ehtiyatının yaradılmasını dəstəkləyir.',
            'nature_text_2': 'Biz istehsala şüurlu şəkildə yanaşır və təbiətin qayğısına qalırıq. Bizim kürümüzü almaqla, siz Xəzər dənizinin təbii ehtiyatlarının bərpa edilməsinə kömək etmiş olursunuz: satılan hər banka ilə biz dənizə 10 kiçik nərə balığı buraxırıq.',
            'buy': 'Haradan almaq olar',
            'buy_text': 'Bizim kürümüzü Bakı şəhərinin və Azərbaycanın ən qabaqcıl otel və restoranlarında ala və dada bilərsiniz. Əgər Baku Caviar kürüsünü şəhərdə əldə edə bilməmisinizsə, hər zaman bunu Bakı şəhərində yerləşən Heydər Əliyev adına Beynəlxalq Hava Limanının Duty Free Shop mağazasında edə bilərsiniz.',
            'menu_1': 'Biz kimik',
            'menu_2': 'İrsimiz',
            'menu_3': 'Bizim kürümüz',
            'menu_4': 'Təbiətə qayğı',
            'menu_5': 'Haradan almaq olar',
            'menu_6': 'Əlaqə',
            'order': 'Kürünü sifariş etmək',
            'name': 'Adınız*',
            'phone': 'Telefon*',
            'adress': 'Ünvan*',
            'caviar': 'Kürü',
            'package': 'Qablaşdırılma və çəki',
            'Tin1': 'Şüşə qab, 20 qr',
            'Tin2': 'Şüşə qab, 50 qr',
            'Tin3': 'Şüşə qab, 125 qr',
            'Tin4': 'Şüşə qab, 250 qr',
            'Tin5': 'Şüşə qab, 500 qr',
            'Tin6': 'Şüşə qab, 1 kq',
            'glass1': 'Şüşə , 56 qr',
            'glass2': 'Şüşə, 113 qr',
            'glass3': 'Şüşə, 250 qr',
            'send': 'Göndər'
        },
        'eng': {
            'h1': 'Natural, Traditional, Delicious, Sustainable',
            'about': 'Who we are',
            'about_text': 'Ever since the days of the Greek philosopher Epicurus, black caviar has been considered synonymous with delicacy and pleasure. After 2000 years, we repeat this principle and make what is called an affordable luxury. Baku Caviar™ is produced from classic Caspian sturgeon. As connoisseurs, we are proud that we manage to maintain high quality and preserve the natural taste.',
            'our': 'Our heritage',
            'our_text': "We trace our history back to 1954 when the world's first sturgeon breeding plant was built in Azerbaijan. It is located in the Neftchala region in a natural reserve on the Caspian coast, and we still produce our products there. In Soviet times, our caviar was supplied to the Kremlin. Also one of the most famous fans of our caviar was Sir Winston Churchill.",
            'our_caviar': 'Our caviar',
            'our_caviar_text': 'The caviar is available in tins of 20, 50, 125, 250, 500 gr, 1 kg and in glass jars of 56 and 113 gr',
            'caviar_text_1': 'Russian sturgeon gives us exceptional caviar, the largest sized eggs. Elastic, with platinum tint and delicate creamy taste, that resembles Beluga caviar. It is extracted from the most valuable, matured and elegant full-grown Russian sturgeons.',
            'caviar_text_2': 'Harvested from first maturity Russian Sturgeon, these amber-shaded caviar eggs are middle-sized and have an incredibly subtle flavour of walnut and cream. It is the most common caviar on the market.',
            'caviar_text_3': 'Beluga is the biggest of sturgeons, and so rare that less than 100 is usually fished out per year. Up to 25% of body weight consists of eggs that can only be spawned when beluga reaches the age of 25–40. Large and grained, eggs vary in colour from nearly black to light grey, and the lighter they are, the more they are valued.',
            'caviar_text_4': 'Sevruga is the third important species among Osetra. Dark, small and distinguished by long snout. Named after the species, this type of caviar is the smallest, the darkest and, according to some experts, the tastiest of all. Sprightly, salt-sea flavour with toasty notes makes it perfect for canapés',
            'caviar_text_5': 'Pressed black caviar, quite rare and exquisite, is a homogeneous, dense and brackish paste. It is made of perfect whole caviar eggs that have radiant black and grey color, and its rich taste has absorbed the essence of black caviar. In the culinary art, it is called ‘caviar truffle’',
            'delivery': 'Delivery',
            'delivery_text': 'You can order our caviar by courier service in Baku. Call us or fill the form online.',
            'delivery_text_btn': 'Order the caviar',
            'nature': 'With care to nature',
            'nature_text_1': 'Sturgeon females need around 8–9 years to reach maturity, and they can live up to 150 years spawning from 250 000 to 400 000 eggs every year. But sturgeons are in danger of extinction. That is why Baku Caviar™ supports creation of marine sanctuary in the mouth of Kura and Aras rivers in Azerbaijan.',
            'nature_text_2': 'We produce responsibly and take care of the environment. Buying from us, you help to restore the nature of the Caspian Sea: we release 10 sturgeon fingerlings into the sea for each can sold.',
            'buy': 'Where to buy',
            'buy_text': 'You can buy and try our caviar in the best hotels and restaurants of Baku city and Azerbaijan. If you didn’t have time or chance to buy Baku Caviar™ in the city, you can find it in Duty Free Shop of Heydar Aliyev International Airport of Baku',
            'menu_1': 'Who we are',
            'menu_2': 'Our heritage',
            'menu_3': 'Our caviar',
            'menu_4': 'With care to nature',
            'menu_5': 'Where to buy',
            'menu_6': 'Contacts',
            'order': 'Order the caviar',
            'name': 'Name*',
            'phone': 'Phone number*',
            'adress': 'Address*',
            'caviar': 'Caviar',
            'package': 'Package and weight',
            'Tin1': 'Tin, 20 g',
            'Tin2': 'Tin, 50 g',
            'Tin3': 'Tin, 125 g',
            'Tin4': 'Tin, 250 g',
            'Tin5': 'Tin, 500 g',
            'Tin6': 'Tin, 1 kg',
            'glass1': 'Glass, 56 g',
            'glass2': 'Glass, 113 g',
            'glass3': 'Glass, 250 g',
            'send': 'Send'
        },
    };

    $(function() {
        $('.translate').click(function() {
            $('.translate').removeClass('active-lang');
            $(this).addClass('active-lang');
            var lang = $(this).attr('id');
            $('.lang').each(function(index, element) {
                $(this).text(arrLang[lang][$(this).attr('key')]);
            });
            console.log('1');
        });
    });

});